### ISSUE TITLE
删除词条功能不能使用

### ISSUE THREAD

**Issue by xana278** [Joenothing-lst/word-bank#4]
删除词条功能不能使用

**Comment by Joenothing-lst** [comment]
请检查自己的权限，以及更详细的描述你所遇到的情况，最好能将这个问题复现一遍。

**Comment by xana278** [comment]
# **更新了最新版本（v1.0.2）问题解决了**

下面是之前码的东西
（v1.0.1）

----
nonebot运行在docker中
# 使用dockerfile 构建镜像
```
FROM python
RUN pip install nb-cli
RUN pip install nonebot-plugin-wordbank
```
# 使用docker-compose运行
```
  nonebot:
    build: /data/my_bot/nonebot/
    image: xana278/nonebot:amd64
    container_name: nb
    network_mode: host
    volumes:
      - "/etc/localtime:/etc/localtime"
      - "/data/my_bot/nonebot:/nonebot"
      # 将data.json 映射到宿主机
      - "/data/my_bot/wb:/usr/local/lib/python3.9/site-packages/nonebot_plugin_wordbank/data/"
    environment: 
      - TIME_ZONE=Asia/Shanghai
    command: sh -c "python bot.py"
    working_dir: /nonebot
    restart: always
```

同理配置好go-cqhttp并连接

# 复现操作 
1. `全局问？答？`
2. 问`？`
3. 答 `？`
4. `删除全局词条`
5. *没有反应*
6. nb logs没有报错
